# Site settings
title: Göksu Bektaş 
description: 'If you can dream it, you can do it.
- Walt Disney'
url: 'http://goksubk.github.io'
baseurl: 'goksubk.github.io'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Göksu Bektaş'
  email: aybikebektass@gmail.com
  twitter_username: goksubektass
  facebook_username: goksu.bektas.771
  github_username:  goksubk
  linkedin_username:  göksu-bektaş-63b55517b

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
